version: '3'
services:
  web:
    image: r.patrick246.de/patrick246/homepage
    build: .
    networks:
      - traefik-net
    deploy:
      labels:
        - "traefik.frontend.rule=Host:patrick246.de,www.patrick246.de"
        - "traefik.docker.network=traefik-net"
networks:
  traefik-net:
    external: true